-- New Hope 7 v2.3.0 — second/final migration
-- Run immediately after nh7_v2_3_0_protected_content.sql

begin;

create table if not exists public.nh7_content_access_log_v230 (
  id bigint generated by default as identity primary key,
  user_id uuid,
  user_email text not null default '',
  content_type text not null,
  content_id text not null,
  device_id text not null default '',
  accessed_at timestamptz not null default now()
);
create index if not exists nh7_content_access_log_v230_user_idx
  on public.nh7_content_access_log_v230(user_email,accessed_at desc);
create index if not exists nh7_content_access_log_v230_content_idx
  on public.nh7_content_access_log_v230(content_type,content_id,accessed_at desc);
alter table public.nh7_content_access_log_v230 enable row level security;
drop policy if exists "NH7 admin read protected content access v230" on public.nh7_content_access_log_v230;
create policy "NH7 admin read protected content access v230"
  on public.nh7_content_access_log_v230
  for select to authenticated
  using (public.nh7_is_admin());

-- Administrators can test protected content without a student registration.
create or replace function public.nh7_my_protected_access_v230()
returns jsonb
language plpgsql
stable
security definer
set search_path='public'
as $$
declare
  v_email text := lower(trim(coalesce(auth.jwt()->>'email','')));
  v_uid uuid := auth.uid();
  v_status text := 'guest';
  v_registration_id uuid;
begin
  if auth.role()<>'authenticated' or v_uid is null or v_email='' then
    return jsonb_build_object('allowed',false,'status','login_required','email',v_email);
  end if;

  if public.nh7_is_admin() then
    return jsonb_build_object(
      'allowed',true,'status','admin','email',v_email,'user_id',v_uid,'registration_id',null
    );
  end if;

  select r.status,r.id
    into v_status,v_registration_id
  from public.registrations r
  where r.type='school'
    and lower(trim(coalesce(r.payload->>'email','')))=v_email
  order by
    case r.status when 'approved' then 0 when 'pending' then 1 else 2 end,
    r.updated_at desc nulls last,
    r.created_at desc nulls last
  limit 1;

  v_status:=coalesce(v_status,'not_registered');
  return jsonb_build_object(
    'allowed',v_status='approved',
    'status',v_status,
    'email',v_email,
    'user_id',v_uid,
    'registration_id',v_registration_id
  );
end;
$$;

revoke all on function public.nh7_my_protected_access_v230() from public;
grant execute on function public.nh7_my_protected_access_v230() to authenticated;

-- School course/lesson metadata and uploaded lesson audio are no longer
-- anonymously queryable. Approved users and administrators retain access.
drop policy if exists "public read active school courses" on public.school_courses;
drop policy if exists "NH7 approved users read school courses v230" on public.school_courses;
create policy "NH7 approved users read school courses v230"
  on public.school_courses for select to authenticated
  using (is_active and (public.nh7_has_protected_access_v230() or public.nh7_is_admin()));

drop policy if exists "public read active school lessons" on public.school_lessons;
drop policy if exists "NH7 approved users read school lessons v230" on public.school_lessons;
create policy "NH7 approved users read school lessons v230"
  on public.school_lessons for select to authenticated
  using (is_active and (public.nh7_has_protected_access_v230() or public.nh7_is_admin()));

revoke select on public.school_courses from anon;
revoke select on public.school_lessons from anon;
grant select on public.school_courses to authenticated;
grant select on public.school_lessons to authenticated;

commit;
